import { useState, useEffect } from 'react';
import { Rule, RuleActionType, ConditionNode, RuleAction } from '@/types/Rule';
import { DataModel, FieldType, DataModelCategory, EnumDefinition } from '@/types/DataModel';
import ConditionTree from './ConditionTree';

interface RuleModalProps {
  isOpen: boolean;
  initialRule: Rule | null;
  dataModels: DataModel[];
  enabledInternalModels: string[];
  enums: EnumDefinition[];
  onClose: () => void;
  onSave: (rule: Rule) => void;
}

// Local UI state for actions (includes ID for React rendering)
interface ActionItem {
  id: string;
  modelName: string;
  fieldName: string;
  value: string;
  valueType: string;
}

export default function RuleModal({ isOpen, initialRule, dataModels, enabledInternalModels, enums, onClose, onSave }: RuleModalProps) {
  const [editingRule, setEditingRule] = useState<Rule | null>(null);
  const [actionItems, setActionItems] = useState<ActionItem[]>([]);

  useEffect(() => {
    if (initialRule) {
      // Initialize with existing conditionNode or create a default root group
      const defaultRoot: ConditionNode = {
          type: 'GROUP',
          logicalOperator: 'AND',
          children: []
      };
      
      setEditingRule({ 
          ...initialRule, 
          conditionNode: initialRule.conditionNode || defaultRoot 
      });

      // Initialize actions
      if (initialRule.ruleActions && initialRule.ruleActions.length > 0) {
          // Use the new structured format
          setActionItems(initialRule.ruleActions.map(ra => ({
              id: crypto.randomUUID(),
              modelName: ra.modelName,
              fieldName: ra.fieldName,
              value: ra.value,
              valueType: ra.valueType
          })));
      } else if (initialRule.action) {
          // Migration support: Parse existing action string into ActionItems
          const items: ActionItem[] = [];
          const regex = /params(?:\.getOutput\(\))?\.put\("([^"]+)",\s*((?:"[^"]*")|(?:\d+(?:\.\d+)?)|(?:true|false))\);/g;
          let match;
          while ((match = regex.exec(initialRule.action)) !== null) {
              const fieldKey = match[1];
              let val = match[2];
              
              // Remove quotes if it's a string value
              if (val.startsWith('"') && val.endsWith('"')) {
                  val = val.slice(1, -1);
              }

              // Try to find the model for this field
              const model = dataModels.find(m => m.category === DataModelCategory.OUTPUT && m.fields.some(f => f.name === fieldKey));
              const field = model?.fields.find(f => f.name === fieldKey);

              items.push({
                  id: crypto.randomUUID(),
                  modelName: model ? model.name : '',
                  fieldName: fieldKey,
                  value: val,
                  valueType: field ? field.type : 'STRING' // Default to STRING if unknown
              });
          }
          if (items.length === 0) {
             items.push({ id: crypto.randomUUID(), modelName: '', fieldName: '', value: '', valueType: 'STRING' });
          }
          setActionItems(items);
      } else {
          setActionItems([]);
      }

    } else {
        setEditingRule(null);
        setActionItems([]);
    }
  }, [initialRule, isOpen, dataModels]);

  if (!isOpen || !editingRule) return null;

  const handleSave = () => {
      if (!editingRule) return;

      // Construct RuleActions from the UI state
      const finalActions: RuleAction[] = actionItems
          .filter(item => item.fieldName && item.value !== '')
          .map(item => ({
              modelName: item.modelName,
              fieldName: item.fieldName,
              value: item.value,
              valueType: item.valueType
          }));
      
      const ruleToSave = { 
          ...editingRule, 
          // We set these to placeholders/comments. The backend will regenerate the safe code from conditionNode and ruleActions.
          condition: '/* Generated by Backend */',
          action: '/* Generated by Backend */',
          ruleActions: finalActions
      };
      onSave(ruleToSave);
  };
  
  const outputModels = dataModels.filter(dm => dm.category === DataModelCategory.OUTPUT);

  const handleAddAction = () => {
      setActionItems([...actionItems, { id: crypto.randomUUID(), modelName: '', fieldName: '', value: '', valueType: 'STRING' }]);
  };

  const handleRemoveAction = (id: string) => {
      setActionItems(actionItems.filter(item => item.id !== id));
  };

  const updateActionItem = (id: string, updates: Partial<ActionItem>) => {
      setActionItems(prev => prev.map(item => {
          if (item.id !== id) return item;
          
          const newItem = { ...item, ...updates };
          
          // If model/field changed, update valueType
          if (updates.modelName || updates.fieldName) {
              const model = dataModels.find(m => m.name === newItem.modelName);
              const field = model?.fields.find(f => f.name === newItem.fieldName);
              if (field) {
                  newItem.valueType = field.type;
              }
          }
          
          return newItem;
      }));
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
        <div className="bg-white dark:bg-slate-900 rounded-lg shadow-xl w-full max-w-5xl p-6 max-h-[90vh] overflow-y-auto">
            <h2 className="text-2xl font-bold mb-4 dark:text-slate-100">Edit Rule</h2>
            
            <div className="grid grid-cols-4 gap-4 mb-4">
                <div>
                    <label className="block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase">ID</label>
                    <input type="text" value={editingRule.id} onChange={e => setEditingRule({...editingRule, id: e.target.value})} className="w-full border dark:border-slate-700 p-2 rounded dark:bg-slate-950 dark:text-slate-100" />
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase">Priority</label>
                    <input type="number" value={editingRule.priority} onChange={e => setEditingRule({...editingRule, priority: parseInt(e.target.value)})} className="w-full border dark:border-slate-700 p-2 rounded dark:bg-slate-950 dark:text-slate-100" />
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase">Action Type</label>
                    <select value={editingRule.actionType} onChange={e => setEditingRule({...editingRule, actionType: e.target.value as RuleActionType})} className="w-full border dark:border-slate-700 p-2 rounded dark:bg-slate-950 dark:text-slate-100">
                        {Object.values(RuleActionType).map(t => <option key={t} value={t}>{t}</option>)}
                    </select>
                </div>
            </div>

            <div className="mb-4">
                <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1">Conditions Tree</label>
                <div className="border dark:border-slate-700 rounded p-2 bg-white dark:bg-slate-900">
                    {editingRule.conditionNode && (
                        <ConditionTree 
                            node={editingRule.conditionNode} 
                            dataModels={[
                                ...dataModels.filter(dm => dm.category === DataModelCategory.INPUT),
                                ...dataModels.filter(dm => dm.category === DataModelCategory.INTERNAL && enabledInternalModels.includes(dm.name))
                            ]}
                            isRoot={true}
                            onChange={(newNode) => setEditingRule({...editingRule, conditionNode: newNode})}
                            onRemove={() => {}} // Root cannot be removed
                        />
                    )}
                </div>
            </div>

            <div className="mb-6">
                <div className="flex justify-between items-center mb-1">
                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300">Actions (Set Outputs)</label>
                    <button onClick={handleAddAction} className="text-xs bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 px-2 py-1 rounded">
                        + Add Output
                    </button>
                </div>
                
                <div className="border dark:border-slate-700 rounded bg-slate-50 dark:bg-slate-800 p-2 space-y-2">
                    {actionItems.map((item, index) => {
                        // Helper to find current field config for this row
                        const currentModel = dataModels.find(m => m.name === item.modelName);
                        const currentField = currentModel?.fields.find(f => f.name === item.fieldName);
                        const currentEnum = currentField?.type === FieldType.ENUM && currentField.enumName 
                                          ? enums.find(e => e.name === currentField.enumName) 
                                          : null;

                        return (
                            <div key={item.id} className="flex gap-2 items-center bg-white dark:bg-slate-900 p-2 rounded border dark:border-slate-700">
                                <div className="w-1/4">
                                    <select 
                                        value={item.modelName} 
                                        onChange={e => updateActionItem(item.id, { modelName: e.target.value, fieldName: '', value: '' })}
                                        className="w-full border dark:border-slate-600 rounded p-1 text-sm dark:bg-slate-950 dark:text-slate-100"
                                    >
                                        <option value="">Select Model...</option>
                                        {outputModels.map(m => <option key={m.name} value={m.name}>{m.name}</option>)}
                                    </select>
                                </div>

                                <div className="w-1/4">
                                    {/* If model selected, show Field Dropdown. If not, show raw input (or disabled dropdown + text display?) */}
                                    {item.modelName ? (
                                        <select 
                                            value={item.fieldName} 
                                            onChange={e => updateActionItem(item.id, { fieldName: e.target.value, value: '' })}
                                            className="w-full border dark:border-slate-600 rounded p-1 text-sm dark:bg-slate-950 dark:text-slate-100"
                                        >
                                            <option value="">Select Field...</option>
                                            {currentModel?.fields.map(f => (
                                                <option key={f.name} value={f.name}>{f.name} ({f.type})</option>
                                            ))}
                                        </select>
                                    ) : (
                                        <input 
                                            type="text"
                                            value={item.fieldName}
                                            disabled
                                            className="w-full border dark:border-slate-600 rounded p-1 text-sm dark:bg-slate-950 dark:text-slate-400 bg-slate-100 italic"
                                            title="Field name (Model not found)"
                                        />
                                    )}
                                </div>

                                <div className="flex-1">
                                    {currentEnum ? (
                                      <select
                                        value={item.value}
                                        onChange={e => updateActionItem(item.id, { value: e.target.value })}
                                        className="w-full border dark:border-slate-600 rounded p-1 text-sm dark:bg-slate-950 dark:text-slate-100"
                                      >
                                        <option value="">Select {currentEnum.name}...</option>
                                        {currentEnum.values.map(v => (
                                          <option key={v} value={v}>{v}</option>
                                        ))}
                                      </select>
                                    ) : (
                                      <input 
                                          type="text" 
                                          value={item.value} 
                                          onChange={e => updateActionItem(item.id, { value: e.target.value })}
                                          disabled={!!item.modelName && !item.fieldName} // Disabled if model selected but field not
                                          className="w-full border dark:border-slate-600 rounded p-1 text-sm dark:bg-slate-950 dark:text-slate-100" 
                                          placeholder="Value"
                                      />
                                    )}
                                </div>
                                
                                <button 
                                    onClick={() => handleRemoveAction(item.id)}
                                    className="text-red-500 hover:text-red-700 px-2"
                                    title="Remove Action"
                                >
                                    ✕
                                </button>
                            </div>
                        );
                    })}
                    
                    {actionItems.length === 0 && (
                        <p className="text-center text-slate-400 text-sm py-2">No actions defined.</p>
                    )}
                </div>
            </div>

            <div className="flex justify-end gap-3">
                <button onClick={onClose} className="px-4 py-2 text-slate-600 dark:text-slate-300 hover:text-slate-800 dark:hover:text-white">Cancel</button>
                <button onClick={handleSave} className="px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">Save Rule</button>
            </div>
        </div>
    </div>
  );
}